### ISSUE TITLE
Klamath and Seattle Shapefiles aren't in Lat/Long

### ISSUE THREAD

**Issue by Velek** [shanet/pirep#112] opened 2023-06-30 23:05 UTC
ogrinfo -al klamath_falls.shp 
INFO: Open of `klamath_falls.shp'
      using driver `ESRI Shapefile' successful.

Layer name: klamath_falls
Geometry: Polygon
Feature Count: 1
Extent: (-341823.426452, -259013.904813) - (347147.655783, 252720.293327)
Layer SRS WKT:
PROJCRS["Lambert_Conformal_Conic",
    BASEGEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101004,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6269]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",42.3333333333333,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",-121,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",46.6666666666667,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",41.3333333333333,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
OGRFeature(klamath_falls):0
  POLYGON ((-317371.580437188 252414.998106055,347147.655783025 252720.293327386,347055.26914433 -250479.001819694,299240.564803026 -252695.577517636,256492.319199873 -254384.397097019,213796.849208576 -255862.11422898,171048.603605423 -256970.402077951,128221.194584487 -257920.363091354,85552.1123991172 -258606.446045479,42812.5980552787 -258955.696418054,14.8753160110191 -259013.904813483,-42710.0869289702 -258984.800615768,-85464.153371666 -258577.341847764,-128218.219814362 -257907.945300329,-170972.286257058 -257034.819368892,-213770.008996325 -255870.65146031,-256480.419142449 -254415.441574582,-299205.381387431 -252756.502304851,-341823.426451688 -250789.710473376,-317371.580437188 252414.998106055))

ogrinfo -al seattle.shp 
INFO: Open of `seattle.shp'
      using driver `ESRI Shapefile' successful.

Layer name: seattle
Geometry: Polygon
Feature Count: 1
Extent: (-318037.182935, -251419.805653) - (346677.092678, 260783.980179)
Layer SRS WKT:
PROJCRS["Lambert_Conformal_Conic",
    BASEGEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101004,
                LENGTHUNIT["metre",1]],
            ID["EPSG",6269]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["Degree",0.0174532925199433]]],
    CONVERSION["unnamed",
        METHOD["Lambert Conic Conformal (2SP)",
            ID["EPSG",9802]],
        PARAMETER["Latitude of false origin",46.75,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8821]],
        PARAMETER["Longitude of false origin",-121,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8822]],
        PARAMETER["Latitude of 1st standard parallel",46.6666666666667,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8823]],
        PARAMETER["Latitude of 2nd standard parallel",41.3333333333333,
            ANGLEUNIT["Degree",0.0174532925199433],
            ID["EPSG",8824]],
        PARAMETER["Easting at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8826]],
        PARAMETER["Northing at false origin",0,
            LENGTHUNIT["metre",1],
            ID["EPSG",8827]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]]
Data axis to CRS axis mapping: 1,2
OGRFeature(seattle):0
  POLYGON ((-293175.798625167 260656.196913488,346677.092678153 260783.980179033,346677.092678153 -251343.485475905,185298.079060573 -251419.805652599,62117.3138778938 -251419.805652599,-61063.4513047852 -251419.805652599,-184396.85684085 -251343.485475905,-318037.18293485 -251350.88928638,-293175.798625167 260656.196913488))

**Comment by shanet** [comment] 2023-06-30 23:09
Hi @Velek, I don't understand what the issue is here or what you're attempting to accomplish.

**Comment by Velek** [comment] 2023-07-01 00:51
In your blog article, you say that all of the shape files have to be in Lat/Long to line up correctly, but these two are in ESRI?

**Comment by shanet** [comment] 2023-07-01 04:56
I'm not following what you mean by needing to be in "Lat/Long." Reprojection is done in the `gdalwarp` step with the `-t_srs EPSG:3857` option so it shouldn't matter what the input format is as that handles converting it to the necessary reference system.

**Comment by N129BZ** [comment] 2023-07-13 17:50
IMHO this is a non-issue. GDAL can reproject between any valid EPSG formats, including what are considered custom PROJCRS like what the FAA uses for charts.  It will even reproject fully customized formats such as the FAA's High and Low IFR charts.

**Comment by shanet** [comment] 2023-07-15 21:37
I don't see the problem here so I'm going to close this. If there's steps to reproduce a demonstrable problem I'm happy to re-open it, but short of that that I don't know what actionable items to take with this.

**Closed by shanet** 2023-07-15 21:37 UTC
